Flavio models -> develop
falker47/BattleShip-frontend pull request #6
Opened 2023-04-22 17:15 UTC by LoggiExp

mi raccomando controllate tutti e tre i cambiamenti e se vi servono i modelli o le chiamate ora ci sono.
Ovviamente non funzionano perchè manca il deploy del backend.

2023-04-22 17:36 UTC, DanieleGhilardini requested changes
Ho commentato riguardo le taglie delle navi, il resto mi pare a posto? Non fidatevi troppo di me...

2023-04-22 17:36 UTC, DanieleGhilardini commented on BattleshipFrontend/src/app/api/models.ts
> +  ship_1_2: Coordinates[]; // Size 1
Sbaglio o ne serve anche una di size 5?

2023-04-22 18:23 UTC, LoggiExp commented on BattleshipFrontend/src/app/api/models.ts
> +  ship_1_2: Coordinates[]; // Size 1
done

2023-04-23 11:41 UTC, falker47 approved these changes

2023-04-23 11:41 UTC, falker47 approved these changes

2023-04-23 11:45 UTC, falker47 approved these changes

2023-04-25 06:57 UTC, DanieleGhilardini approved these changes

2023-04-25 07:09 UTC, merged